### ISSUE TITLE
Minigame: Aim Master Rework

### ISSUE THREAD

**Issue by LCLPYT** [LCLPYT/arcade-party-2#26]
# General Tasks
- [x] define map properties (viewer position, view cone fov, view cone direction vector, block radius)
- [x] generate a sequence of randomized block constellations that every player will see -> complete block generator tasks first
- [x] decide how the sequence blocks have to be clicked. Define either a block that should be clicked for each constellation, or implement a different behaviour of how the blocks must be clicked
- [x] create a VirtualBlocks class that tracks "virtual" blocks in the world The class should be backed by a `Map<BlockPos, BlockState>` that stores virtual blocks in their absolute positions
- [x] create a `List<VirtualBlocks>` that represents the sequence of block constellations, generated earlier
- [x] create a `AimMasterManager` class that keeps track of the progress for each player. The class should be backed by a `Map<UUID, Integer>` representing the sequence item, each player is currently at (UUID of the player is stored). Also, the class should hold a reference to the VirtualBlocks sequence list, generated earlier (`List<VirtualBlocks>`)
- [x] implement two methods in the `VirtualBlocks` class, `void placeFor(ServerPlayerEntity)` and `void destroyFor(ServerPlayerEntity)` both methods should send packets to the player, so that they can see the virtual blocks (-> `BlockUpdateS2CPacket`)
- [x] each time a player advances to a new block constellation, the old `VirtualBlocks` instance must be destroyed for that player and the new `VirtualBlocks` instance has to be placed for that player
- [x] use the `RayCaster` class from `mg-lobby` to determine the block a player is aiming at. Use `PlayerInteractionHooks` to trigger raycasting when a player does an interaction (a new hook may has to be introduced in `kibu` in order to listen to attacking misses or left clicks)
- [x] implement a win condition, e.g. if a player reached 20 points or something similar
- [x] track the points of players in a `ScoreTimeDataContainer`

# Block Generator
The blocks should be generated on the sphere projection of a view cone.
The sphere is centered on the configured viewer position and has the configured block radius.
The tip of the view cone is also the configured viewer position and the configured view cone direction vector is pointing towards the base of the cone (which is projected on the sphere).

As first approach the block positions can be determined by iterating over a `BlockBox` (use the one from ArcadeParty, not MC!) that encompasses the sphere.
For each position inside that box, filter out positions that are not on the sphere or that are not inside the view cone.
Check whether a BlockPos is on the sphere, by calculating the squared distance towards the viewer position:
```
squaredDistance = Δx² + Δy² + Δz²
```
Where Δx is (viewerPos.x - pos.x) etc.
Then, compare the squared radius to the squaredDistance. If the difference between the two is smaller than a specific ε, then the block position is on the sphere.
```
onSphere = abs(squaredDistance - radius²) < ε
```
Choose ε as seen fit.
Debug the sphere generation by placing blocks (`world.setBlockState(pos, Blocks.RED_WOOL.getDefaultState())` on the genrated sphere positions. The result should be a hollow sphere.

In the next step, the positions must be filtered, so that they are in the view cone.
For that, calculate the angle between the view cone direction vector and the vector between the viewer position and the block position in question.
```
vec = pos - viewerPos
angle = acos(dot(vec, viewDir) / (vec.length * viewDir.length))
```

If the angle is less or equal than the configured view cone fov, the block is inside the view cone.

Debug the new position generator too by placing test blocks.
If everything is working as expected, add every position to a List and pick random elements from it (without duplicates).

## Tasks
- [x] construct a `BlockBox` that encompasses the sphere
- [x] iterate over every position in the box (`for (BlockPos pos : box)`)
- [x] filter positions, so that only positions on the sphere are picked
- [x] debug sphere filter by placing blocks on the positions
- [x] filter positions, so that only positions in the view cone are picked
- [x] debug view cone filter by placing blocks
- [x] construct a list of remaining positions (remember to create immutable copies of the block positions, before adding them to the list: `list.add(pos.toImmutable())`
- [x] pick some amount of distinct positions randomly (e.g. remove an element from the list when it was picked by the RNG)
